services:
  pricewatch:
    image: builder555/pricewatch:latest
    container_name: pricewatch
    env_file:
      - .env
    volumes:
      - ./items.json:/app/app/db/items.json
    ports:
      - 8700:8700

