name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  ignore-readme-only-changes:
    runs-on: ubuntu-latest
    outputs:
      run_build: ${{ steps.filter.outputs.run_build }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - id: filter
        name: Check if README.md was updated
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -iqvE '^(readme.md)$'
          then
            echo "run_build=true" >> $GITHUB_STATE
          else
            echo "run_build=false" >> $GITHUB_STATE
          fi

  build-and-push:
    needs: ignore-readme-only-changes
    if: needs.check-modified-files.outputs.run_build == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Check for README.md changes
        id: readme_check
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -v 'README.md'
          then
            echo "README_CHANGE=false" >> $GITHUB_ENV
          else
            echo "README_CHANGE=true" >> $GITHUB_ENV
          fi
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: builder555
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push multi-platform Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: builder555/pricewatch:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7
